CREATE TABLE bootcamps (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  url TEXT NOT NULL
);

--https://techbeacon.com/app-dev-testing/complete-guide-24-coding-bootcamps
