CREATE TABLE locations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  city TEXT NOT NULL,
  state TEXT NOT NULL
  -- bootcamp_id INTEGER,
  --   FOREIGN KEY (bootcamp_id) REFERENCES bootcamps(bootcamp_id)
);

--bootcamps can have many locations. there can also be many bootcamps in one
--location. (many-to-many). Need to create another table and put a FK in bootcamps
--and another here that references this unique table? 