CREATE TABLE courses (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  is_online BOOLEAN, --is the course offered online?
  solo_instruction BOOLEAN, --is there one-on-one time with instructors/TAs
  pair_programming BOOLEAN, --is there student pair programming?
  prior_experience BOOLEAN --does the course require prerequisites or prior exp?
);

