CREATE TABLE bootcamp_courses (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bootcamp_id INTEGER REFERENCES bootcamps(id),
  name TEXT NOT NULL,
  style TEXT NOT NULL, --in person, online, combination
  schedule TEXT NOT NULL, --full-time, part-time, flexible
  stack TEXT NOT NULL, --full stack, front-end, back-end 
  duration INTEGER NOT NULL, --weeks/months
  mentorship TEXT,
  job_guarantee TEXT,
  career_assistance TEXT,
  placement_rate DECIMAL(4,2) --xx.xx
);

--bootcamps can have many course offerings - One-to-many