CREATE TABLE payment_summaries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES bootcamp_courses(id),
  monthly FLOAT,
  up_front FLOAT,
  interest_only_loan TEXT,
  immediate_repayment_loan TEXT,
  isa TEXT
);

--a course can have many payment options - One-to-many. 