CREATE TABLE payment_summaries (
  id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES bootcamp_courses(id),
  monthly FLOAT(n),
  up_front FLOAT(n),
  interest_only_loan TEXT,
  immediate_repayment_loan TEXT,
  isa TEXT
);

--a course can have many payment options - One-to-many. 