CREATE TABLE course_languages (
  language_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES bootcamp_courses(id)
  language TEXT NOT NULL, --javascript, python, ruby etc.
);

