CREATE TABLE course_schedules (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES courses(id),
  schedule TEXT NOT NULL, --full_time, part_time, flexible
  hours INTEGER NOT NULL,--hours per week
  duration INTEGER --length of program in weeks
);
