CREATE TABLE course_frameworks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES bootcamp_courses(id)
  framework TEXT NOT NULL, -- Express(node.js), AngularJS, Vue.js, Django etc.
)
