CREATE TABLE payment_summaries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER REFERENCES courses(id),
  up_front FLOAT,  
  financing BOOLEAN,
  isa BOOLEAN, --income sharing agreement: provide % of your first/second year salary
  placement_based BOOLEAN, --no money up front until you get a job making over X
  repayment_guarantee BOOLEAN -- money back guarantee if you dont get a job within X months
);

