INSERT INTO locations (city, state)
VALUES
('Atlanta', 'GA'),
('Austin', 'TX'), 
('Boston', 'MA'),
('Charlotte', 'NC'),
('Chicago', 'IL'),
('Dallas', 'TX'),
('Denver', 'CO'), 
('Detroit', 'MI'),
('Houston', 'TX'),
('Kernersville', 'NC'), 
('Los Angeles', 'CA'), 
('Louisville', 'KY'),
('Milwaukee', 'WI'), 
('Minneapolis', 'MN'), 
('Nashville', 'TN'), 
('New York City', 'NY'),
('Miami', 'FL'),
('Oakland', 'CA'),
('Orlando', 'FL'),
('Phoenix', 'AZ'),
('Portland', 'OR'), 
('Providence', 'RI'),
('Raleigh', 'NC'),
('Renton', 'WA'),
('Salt Lake City', 'UT'),
('San Diego', 'CA'),
('San Francisco', 'CA'),
('Seattle', 'WA'),
('Stamford', 'CT'),
('St. Louis', 'MO'),
('Tampa', 'FL'),
('Washington', 'DC'),
('Wheat Ridge', 'CO');

