INSERT INTO courses 
(
    name, 
    is_online, 
    solo_instruction, 
    pair_programming, 
    prior_experience
)
VALUES
('Full-stack Web Development', true, true, true, false), --course 1
('24 Week Software Engineering Immersive', true, true, true, false),
('16 Week Software Engineering Immersive', false, true, true, false),
('Code 102: Intro to Software Development', false, true, true, false),
('Code 201: Foundations of Software Development', false, true, true, true),
('Code 301: Intermediate Software Development', false, true, true, true),
('Code 401: Advanced Software Development in Full-Stack Javascript', false, true, true, true),
('Code 401: Advanced Software Development in Python', false, true, true, true),
('Code 401: Advanced Software Development in ASP.NET Core', false, true, true, true),
('Code 401: Advanced Software Development for Mobile Applications', false, true, true, true),
('Code 401: Advanced Software Development in Java with SpringMVC & Android', false, true, true, true),
('Full-stack Web Developer', true, true, true, false), 
('Full-stack .NET Development', false, true, true, false), 
('Software Engineering Immersive', false, true, true, true), 
('CSPrep', true, true, true, false), 
('Javascript for Beginners', true, true, true, false), 
('Full-stack Python and Data Science', true, true, true, false), 
('Full-stack Web Development', true, true, true, false),
('Software Development', false, true, true, false), 
('Full-stack Web Development', false, true, true, true), 
('Intro to Programming', true, true, true, false), 
('Javascript/React and C#/.NET or Ruby/Rails', false, true, true, false), 
('Introduction to Coding', true, true, true, false), 
('Full-Time Coding Bootcamp', true, true, true, true), 
('Part-Time Flex Coding Bootcamp', true, true, true, false), 
('Grace Hopper Program', true, true, true, false), 
('Online Coding Bootcamp', true, true, true, false), 
('Software Engineering Immersive', true, true, true, false), 
('User Experience Design Immersive', true, true, true, false), 
('Data Science Immersive', true, true, true, false), 
('Python Programming', true, true, true, false), 
('User Experience Design', true, true, true, false), 
('Data Analytics', true, true, true, false),
('Data Science', true, true, true, false),
('Front-End Web Development', true, true, true, false), 
('Javascript Development', true, true, true, false), 
('React Development', true, true, true, false),
('Web Development', true, true, true, false), 
('UX Design', true, true, true, false), 
('Data Analytics', true, true, true, false), 
('Kickstart Backend', false, true, true, false), 
('Kickstart Frontend', false, true, true, false), 
('Kickstart Online', true, true, true, false), 
('Full-stack Web Development', true, true, true, false), 
('Full-stack Web Development', false, true, true, false), 
('Java and .NET/C#', true, true, true, false), 
('Engineering Immersion', true, true, true, false), 
('Engineering Flex', true, true, true, false),
('UX/UI Design Immersion', true, true, true, false), 
('UX/UI Design Flex', true, true, true, false), 
('Data Science Immersion', true, true, true, false), 
('Data Science Flex', true, true, true, false), 
('Data Analytics Immersion', true, true, true, false), 
('Data Analytics Flex', true, true, true, false), 
('Full-stack Development', true, true, true, false), 
('Front-End Development', true, true, true, false);




